meta_product_name: "InfluenceHorizons"
meta_title: "InfluenceHorizons - Influencer collaborations for regional businesses"
meta_description: "With InfluenceHorizons, you can easily find suitable influencers to collaborate and reach new customers with authentic marketing."
meta_image: "IMG_lake.jpg" # should exist in `app/assets/images/`
